generator/src/googleapis/codegen/languages/java/1.26.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.27.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/default/templates/_pom_xml.tmpl, synth.py
At codegen time, we copy the discovery document to the resources folder. This folder is now configured to be included as a resource in the resulting jar.
We will want to regenerate all the clients after merging.
=> Provide a copy of the discovery document as a resource

generator/src/googleapis/codegen/api.py
Always process schemas in alphabetical order.
This allows the schema reference algorithm to be consistent and avoids
the Proguard hack thrashing.
Fixes #51 
We will want to rebuild all the clients after the PR to avoid having 100+ PRs from autosynth fixing the order.
=> Fix Proguard hack thrashing during codegen

generator/src/googleapis/codegen/utilities/name_validator.py, generator/tests/utilities/name_validator_test.py
Allows `$` in the middle of parameter names to enable an upcoming API release.
=> Allow $ in model field names

.kokoro/release.sh
The docs should be uploaded as google-api-services-x rather than just x.
=> Fix doc uploader service name

synth.py
Fixes #3222 
When deleting an entire client that has multiple versions (e.g. fusiontables), we end up trying to run rmtree twice on the same directory. The second execution fails and causes the entire synth job to fail.
=> fix(synth): ignore rmtree errors when deleting an entire client

README.md
There are several pages that point to this README.md for documentation, but it's unclear what is the best way to perform authentication.  Web searches push towards [google-oauth-java-client](google-oauth-java-client) library which is now in maintenance mode.
=> Add link to google-auth-library-java

README.md
The Google auth library link was broken and was pointing to the wrong link, so I fixed it.
=> Fixed link to Google auth library in Readme

generator/generate.sh
Creates a bash script in the generator directory to make it easy to self-serve discovery client generation.
Usage:
1. Clone this repository
2. Run the generate.sh script:
```bash
generator/generate.sh <discovery> <output-directory>
```
3. compile the jar:
```bash
cd <output-directory>
mvn package
```
The output jar will be available in `<output-directory>/target`
The `discovery` option can either be a path to the json discovery file or a url to fetch from. The client will be generated in the `output-directory`.
Note that the generator still requires python2.
=> feat: add script for easy self-serve client generation

.github/CODEOWNERS, .github/sync-repo-settings.yaml, .github/workflows/auto-approve.yaml
Setup require checks and team permissions via sync-repo-settings.
Use yoshi-approver bot for auto-approve.
=> build: configure CODEOWNERS

generator/src/googleapis/codegen/api.py, generator/tests/api_test.py, synth.py
- use regex to generate mtls endpoint if `mtlsRootUrl` is missing from discovery doc
- update the template version in synth.py to generate 1.31.0 client libraries
=> build(generator): add mtls endpoint fallback and update synth.py template version

.github/workflows/generate.sh
`adsensehost.v4.1.json` was being parsed as `v4` when it should have been `v4.1`
This change strips off the trailing `.json` and then splits on `.` and returns the second token and beyond
=> build: fix version parsing

generator/src/googleapis/codegen/languages/java/1.31.0/features.json, generator/src/googleapis/codegen/languages/java/1.31.0/templates/_pom_xml.tmpl
This should prevent us having 200+ PRs to revert versions
=> build: update template to match compiler and api client version

renovate.json
We should not be using renovate to bump dependency versions.
Dependency versions are managed by templates and will be reverted by codegen if we update via renovate.
=> build: disable renovate

generator/src/googleapis/codegen/languages/java/1.31.0/templates/README.md.tmpl, generator/src/googleapis/codegen/languages/java/default/templates/README.md.tmpl
Fixes https://github.com/googleapis/google-api-java-client-services/issues/9537
=> chore: use 'implementation' instead of 'compile' for dependencies

clients/google-api-services-admin/datatransfer_v1/1.30.1/README.md, clients/google-api-services-admin/datatransfer_v1/1.31.0/README.md, clients/google-api-services-admin/datatransfer_v1/README.md, clients/google-api-services-admin/directory_v1/1.30.1/README.md, clients/google-api-services-admin/directory_v1/1.31.0/README.md, clients/google-api-services-admin/directory_v1/README.md, clients/google-api-services-admin/reports_v1/1.30.1/README.md, clients/google-api-services-admin/reports_v1/1.31.0/README.md, clients/google-api-services-admin/reports_v1/README.md
Fixes #6100
These are all getting uploaded with the name 'google-api-services-admin' and differentiate on version. If you look at the dropdown at [googleapis.dev/java/google-api-services-admin/latest/index.html](https://googleapis.dev/java/google-api-services-admin/latest/index.html) you can see they exist as different versions. We'd have to configure this differently to make it work https://github.com/googleapis/google-api-java-client-services/blob/main/.kokoro/release.sh#L60 and I'm not sure it's worth it for apiary. It's annoying because you can't just link to latest, you have to link to the specific version.
Since they are all grouped together the latest is getting chosen as the reports one likely because it has the highest number. These pages exist, just a little confusing to …
=> chore: update javadoc link

.github/workflows/generate.sh
It seems that the template directory "2.0.0" is unused yet in the codegen job https://github.com/googleapis/google-api-java-client-services/runs/7602652259?check_suite_focus=true.
=> build: generate.sh to use variant "2.0.0"

renovate.json
This enables Renovate Bot to update versions in `2.0.0/features.json` for: baseClientLibrary, oauthClientLibrary, httpClientLibrary, gsonVersion, httpClientVersion, jackson2CoreVersion.
Configuration tested here: https://github.com/meltsufin/renovate-test/issues/1.
=> chore(deps): enable Renovate Bot for 2.0.0

README.md
The other day, I found it difficult to setup authentication but the authentication library has the exact code I wanted to learn.
- The link should point to the authentication with google-http-client
- The API documentation is now at https://cloud.google.com/java/docs/reference/google-auth-library/latest/overview.
=> docs: updating google-auth-library links

.github/workflows/codegen.yaml
The current generation job fails conventional commit check (which recently added to googleapis):
=> ci: generation job to follow conventional commit

.github/workflows/codegen.yaml
The codegen job has been failing due to 
> Error: Version 2.7 with arch x64 not found
> The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
Version 2.7.18 is available as per  https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
Fixes https://github.com/googleapis/google-api-java-client-services/issues/13409
=> ci: fixing GitHub Actions python version

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support_request.md
Overwrites the issue templates found in https://github.com/googleapis/.github/tree/main/.github/ISSUE_TEMPLATE.
=> chore: add issue templates for repo

.github/workflows/codegen.yaml, .github/workflows/generate.yaml
Fixes [#16186](https://github.com/googleapis/google-api-java-client-services/issues/16186)
Also splits the services in batches of size 100. 
Each batch will be run at its own index based on the current hour. For example, if it's 01:30am then it will run `batches[1]`
=> fix: generate batches at separate times

.github/workflows/codegen.yaml
The current codegen.yaml generates clients in 4 batches and 100 clients per batch, which makes the last batch always succeeds due to the number of services is less than 300 at this moment.  Changing the batch size to 2 and number of clients per batch to 200 so that the build status is correctly reflected. 
We need to manually increase the batch size once the number of clients is greater than 400, but it should be years from now.
=> fix: Update codegen.yaml to generate clients in 2 batches and 200 clients per batch

generator/src/googleapis/codegen/languages/java/2.0.0/templates/_method.tmpl
Reproducer Code with `com.google.apis:google-api-services-drive:v3-rev20230822-2.0.0`:
```
GoogleCredentials credentials = GoogleCredentials.getApplicationDefault()
.createScoped(Arrays.asList(DriveScopes.DRIVE_FILE));
HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(
credentials);
// Build a new authorized API client service.
Drive drive = new Drive.Builder(new NetHttpTransport(),
GsonFactory.getDefaultInstance(),
requestInitializer)
.setApplicationName("Drive samples")
.build();
File file = new File();
drive.files().update("test", file, null);
```
Results in:
```
Exception in thread "main" java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
at com.google.api.client.util.Preconditions.checkNotNull(Preconditions. …
```
=> fix: MediaContent is a non-nullable parameter

.github/workflows/generate.sh
The latest variant's README will be copied over to the library's root README on generation. Hardcode the latest version to be 2.0.0 (which will need to be updated if a new variant is created). 
Variant is set to be the latest variant (i.e. `2.0.0`) if there is no variant input, which allows us to generate new clients for old variants (i.e. `1.x.x`) if it's ever needed. Generating older variants would not have the README be copied over to the library's root README section.
Fixes: https://github.com/googleapis/google-api-java-client-services/issues/16629
=> fix: Copy latest variant's README to root README

.github/workflows/generate.sh
Fixes #18823 ☕ 
This PR replaces the whole contents of a library with the new generated source code, causing deleted messages (via disc doc) to be deleted. This is the same behavior as GAPIC libraries
Confirmation after calling `.github/workflows/generate.sh playintegrity` produced the following modification
```
On branch generation-overwrite-fix
Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
deleted:    ../../clients/google-api-services-playintegrity/v1/2.0.0/com/google/api/services/playintegrity/v1/model/AccountRiskVerdict.java
no changes added to commit (use "git add" and/or "git commit -a")
```
=> fix: replace whole library source when generating libraries

.kokoro/test.sh
Part of issue in b/307942373
An example of a previous run: https://source.cloud.google.com/results/invocations/c53db7a4-af9f-40b2-ba85-29cd10dd1808/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-api-java-client-services%2Fpresubmit/log
Has logs:
```
/tmpfs/src/github/google-api-java-client-services /tmpfs/src
/tmpfs/src/github/google-api-java-client-services/clients/google-api-services-abusiveexperiencereport/v1/1.26.0 /tmpfs/src/github/google-api-java-client-services /tmpfs/src
error: Could not access 'master'
No difference from master, skipping tests.
/tmpfs/src/github/google-api-java-client-services /tmpfs/src
/tmpfs/src/github/google-api-java-client-services/clients/google-api-services-abusiveexperiencereport/v1/1.27.0 /tmpfs/src/github/google-api-java-client-services …
```
=> ci: Fix test CI job

.kokoro/test.sh, clients/google-api-services-abusiveexperiencereport/v1/2.0.0/com/google/api/services/abusiveexperiencereport/v1/AbusiveExperienceReportRequest.java
Logs from latest run:
```
Found differences in clients/google-api-services-translate/v3/2.0.0. Compiling...
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.google.apis:google-api-services-parent >-------------
[INFO] Building Google APIs Client Library for Java 0.0.1-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ google-api-services-parent ---
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom (4.1 kB at 6.7 kB/s)
[INFO] Downloading from central: …
```
=> ci: Run mvn verify in the client directory

README.md
Adding a pointer about the origin of discovery document, so that future troubleshooter can find the information of the origin of the discovery document.
=> chore: a pointer about the origin of discovery document

.github/workflows/verify.yaml, .github/workflows/verify_compilation.sh
This new check runs at 4am every day and runs `mvn compile` on every client at the service-version level on template version 2.0.0 only. For example it would run once for
```
/google-api-services-example/v1/2.0.0
/google-api-services-example/v2/2.0.0
```
But it would not run for 
```
/google-api-services-example/v1/1.31.0
/google-api-services-example/v2/1.31.0
```
The compilations are run in parallel (max 50 jobs)
Every compilation failure will be printed at the end of the workflow ([example](https://github.com/diegomarquezp/google-api-java-client-services/actions/runs/8898906658)).
The last part of the workflow output is what matters:
```
2024-04-30T18:40:09.0018589Z The following libraries had compilation errors:
2024-04-30T18:40:09.0019604Z + echo 'The following libraries had …
```
=> chore: add check to create list of non-compilable libraries

.github/workflows/codegen.yaml
Based on the [public doc](https://cloud.google.com/document-warehouse/docs/overview) of contentwarehouse, it is deprecated, we should remove it from our daily generation.
=> chore: Exclude contentwarehouse from daily generation.

.github/workflows/generate.yaml, README.md
Pointing to the team document because the content is irrelevant to library users.
=> chore: readme's "how the code is updated" to point to team document

README.md
We launched the google wallet api bindings at the beginning of the year, but they are not listed in the README
=> fix: Update README.md to include Wallet API links

generator/src/googleapis/codegen/api.py
in the case that there is global parameter and its redeclared in the individual method declaration, remove the duplicate #19018 
after running generator with the new build it removes the second setKey function and only keeps the global function
` @Override
public RetrieveLegacySecretKey setKey(java.lang.String key) {
return (RetrieveLegacySecretKey) super.setKey(key);
}
`
output of compilation
`[INFO] Installing /Users/ldetmer/workspace/google-api-java-client-services/generator/src/tmp/target/google-api-services-recaptchaenterprise-v1-rev20220505-2.0.0-javadoc.jar to /Users/ldetmer/.m2/repository/com/google/apis/google-api-services-recaptchaenterprise/v1-rev20220505-2.0.0/google-api-services-recaptchaenterprise-v1-rev20220505-2.0.0-javadoc.jar
[INFO] …
=> fix: remove duplicate set param functions when param exists in parent

generator/README
The minimum version to run the Apiary generator is now 3.6 per https://github.com/googleapis/google-api-java-client-services/pull/21574. Update the README to reflect it.
=> docs: Update README with the new minimum Python version 3.6

.github/workflows/generate.yaml
This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467
=> Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

.github/workflows/codegen.yaml
See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
> The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. If the load is sufficiently high enough, some queued jobs may be dropped. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
=> chore: use less concurred minute of hour for scheduled jobs

.github/workflows/generate.yaml
As python gets updated, it will no longer work with the version of pip we need to use 'django.utils.six.moves'.
so lock in python + pip for now.  ideally we would move away from djiango 
tested [here](https://github.com/googleapis/google-api-java-client-services/actions/runs/14539912149)
=> fix:  generate action not working

generator/src/googleapis/codegen/languages/java/1.26.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.27.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.28.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.29.2/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.30.1/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.31.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/2.0.0/templates/_pom_xml.tmpl
This PR includes:
- A profile to avoid using nexus-staging-maven-plugin.
- A profile to upload to GCP Artifact Registry.
Following https://github.com/googleapis/google-oauth-java-client/pull/1132
=> chore: profile to avoid using nexus-staging-maven-plugin

generator/src/googleapis/codegen/languages/java/1.26.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.27.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.28.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.29.2/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.30.1/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/1.31.0/templates/_pom_xml.tmpl, generator/src/googleapis/codegen/languages/java/2.0.0/templates/_pom_xml.tmpl
To address the following issue with the release:
```
"errors":{"pkg:maven/com.google.apis/google-api-services-alloydb@v1-rev20250605-2.0.0":["Namespace 'com.google.apis' is not allowed","Developers information is missing"]}}
```
Context: https://central.sonatype.org/publish/requirements/#developer-information
The developer id information is the same as https://github.com/googleapis/sdk-platform-java/blob/71da6c077d745d4c248eb122fcf9920ee0df772f/gax-java/pom.xml#L18-L26
This change has been verified with v1 alloydb in https://github.com/googleapis/google-api-java-client-services/pull/27633.
=> chore: add developer info to pom templates

clients/google-api-services-storage/v1/2.0.0/README.md, clients/google-api-services-storage/v1/2.0.0/pom.xml, clients/google-api-services-storage/v1/README.md
The existing storage version v1-rev20250814-2.0.0 has google-api-client v2.8.1. The downgraded google-api-client version didn't trigger an update to the versionId and isn't released to Maven Central:
https://central.sonatype.com/artifact/com.google.apis/google-api-services-storage/v1-rev20250814-2.0.0
=> chore: Manually bump storage version to v1-rev20250815-2.0.0
